remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme
title: Melinda Higgins, PhD
description: Director of Biostatistics and Data Core - ONR; Research Professor

# theme: jekyll-theme-minimal
# plugins:
#   - jemoji
# title: Melinda Higgins, PhD
# description: Director of Biostatistics and Data Core - ONR; Research Professor
# markdown: kramdown

# remote_theme: pages-themes/dinky@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

# theme: jekyll-theme-minimal
# title: Melinda Higgins, PhD
# description: Director of Biostatistics and Data Core - ONR; Research Professor
# logo: https://assets-global.website-files.com/5f11b12012400490893a64ea/5f11b1201240041bcb3a6700_higgin.jpg
